//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace probniy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int AgentID { get; set; }
        public string AgentType { get; set; }
        public string AgentName { get; set; }
        public string AgentEmail { get; set; }
        public string AgentPhone { get; set; }
        public string AgentLogo { get; set; }
        public string AgentAddress { get; set; }
        public int AgentPrioritet { get; set; }
        public string Director { get; set; }
        public string AgentINN { get; set; }
        public string AgentKPP { get; set; }
    }
}
