//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace probniy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string AgentName { get; set; }
        public System.DateTime DateOfRelease { get; set; }
        public int ProductCount { get; set; }
    }
}
